version: "3.8"

services:
  utils4dev-postgres:
    image: bitnami/postgresql:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - utils4dev-network
    restart: unless-stopped

  utils4dev-api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEB_URL=${WEB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - utils4dev-network
    depends_on:
      - utils4dev-postgres

  utils4dev-web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
    networks:
      - utils4dev-network
    depends_on:
      - utils4dev-api

volumes:
  postgres_data:
    driver: local

networks:
  utils4dev-network:
    driver: bridge
