version: "3.8"

services:
  utils4dev-postgres:
    image: bitnami/postgresql:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - utils4dev-network
    restart: unless-stopped

  utils4dev-api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEB_URL=${WEB_URL}
      - DOMAIN_URL=${BACKEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - utils4dev-network
      - traefik-proxy
    depends_on:
      - utils4dev-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.utils4dev-api-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.utils4dev-api.rule=Host(`utils4dev.${DOMAIN}`) && PathPrefix(`/${API_PATH_PREFIX}`)"
      - "traefik.http.routers.utils4dev-api.priority=100"
      - "traefik.http.routers.utils4dev-api.entrypoints=websecure"
      - "traefik.http.routers.utils4dev-api.tls=true"
      - "traefik.http.routers.utils4dev-api.tls.certresolver=letsencrypt"

  utils4dev-web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
    networks:
      - utils4dev-network
      - traefik-proxy
    depends_on:
      - utils4dev-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.utils4dev-web-service.loadbalancer.server.port=80"
      - "traefik.http.routers.utils4dev-web.rule=Host(`utils4dev.${DOMAIN}`)"
      - "traefik.http.routers.utils4dev-web.priority=10"
      - "traefik.http.routers.utils4dev-web.entrypoints=websecure"
      - "traefik.http.routers.utils4dev-web.tls=true"
      - "traefik.http.routers.utils4dev-web.tls.certresolver=letsencrypt"

volumes:
  postgres_data:
    driver: local

networks:
  utils4dev-network:
    driver: bridge
  traefik-proxy:
    external: true
