/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export type AddCodeReactionDtoType = typeof AddCodeReactionDtoType[keyof typeof AddCodeReactionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddCodeReactionDtoType = {
  like: 'like',
  dislike: 'dislike',
} as const;
