/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { ReactionType } from './reactionType';

export interface AddCodeReactionDto {
  type: ReactionType;
}
