/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { ReactionType } from './reactionType';

export interface CodeReactionDto {
  type: ReactionType;
  id: string;
}
