/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export type CodeWithReactionsDtoReactions = {[key: string]: {
  length?: number;
  userReacted?: boolean;
}};
