/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export type CodeLanguage = typeof CodeLanguage[keyof typeof CodeLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodeLanguage = {
  TypeScript: 'TypeScript',
  JavaScript: 'JavaScript',
  GraphQL: 'GraphQL',
} as const;
