/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';

export interface CommentDto {
  id: string;
  content: string;
  createdAt: string;
  author: UserDto;
}
