/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { CodeLanguage } from './codeLanguage';

export interface CreateCodeDto {
  language: CodeLanguage;
  name: string;
  content?: string;
  private: boolean;
}
