/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { FindAllPublicCodesLanguageItem } from './findAllPublicCodesLanguageItem';

export type FindAllPublicCodesParams = {
authorId?: string;
language?: FindAllPublicCodesLanguageItem[];
name?: string;
};
