/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export type FindAllPublicCodesLanguageItem = typeof FindAllPublicCodesLanguageItem[keyof typeof FindAllPublicCodesLanguageItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAllPublicCodesLanguageItem = {
  TypeScript: 'TypeScript',
  JavaScript: 'JavaScript',
  GraphQL: 'GraphQL',
} as const;
