/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { FindMyCodesLanguageItem } from './findMyCodesLanguageItem';

export type FindMyCodesParams = {
language?: FindMyCodesLanguageItem[];
name?: string;
};
