/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */
import type { GetBookmarkCodesLanguageItem } from './getBookmarkCodesLanguageItem';

export type GetBookmarkCodesParams = {
language?: GetBookmarkCodesLanguageItem[];
name?: string;
};
