/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export type ReactionType = typeof ReactionType[keyof typeof ReactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReactionType = {
  like: 'like',
  dislike: 'dislike',
} as const;
