/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Utils4Dev
 * OpenAPI spec version: 1.0
 */

export interface UpdateCodeDto {
  keywords?: string[];
  description?: string;
  name?: string;
  content?: string;
  private?: boolean;
}
